#release configuration
#Fri Apr 17 13:35:40 JST 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.elephant\:elephant=0.7.2-SNAPSHOT
project.rel.org.elephant\:elephant=0.7.1
project.scm.org.elephant\:elephant.connection=scm\:git\:git\://github.com/elephant-track/elephant-client
project.scm.org.elephant\:elephant.developerConnection=scm\:git\:git@github.com\:elephant-track/elephant-client
project.scm.org.elephant\:elephant.tag=HEAD
project.scm.org.elephant\:elephant.url=https\://github.com/elephant-track/elephant-client
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=elephant-0.7.1
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/elephant-track/elephant-client
